package com.ewaste.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.index.Indexed;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

/**
 * User Entity - Represents a user in the system
 * 
 * @Document: Marks this class as a MongoDB document (collection: users)
 * @Data: Lombok annotation - generates getters, setters, toString, equals, hashCode
 * @NoArgsConstructor: Generates no-argument constructor
 * @AllArgsConstructor: Generates constructor with all fields
 * 
 * MongoDB Collection: users
 */
@Document(collection = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Primary Key - MongoDB ObjectId
     * Automatically generated by MongoDB
     */
    @Id
    private String id;

    /**
     * User's full name
     * Required field with minimum length of 2 characters
     */
    @NotBlank(message = "Name is required")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    private String name;

    /**
     * User's email address
     * Must be unique, valid email format, and indexed for fast lookups
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    @Indexed(unique = true)
    private String email;

    /**
     * User's phone number
     * Required field
     */
    @NotBlank(message = "Phone number is required")
    @Size(min = 10, max = 15, message = "Phone number must be between 10 and 15 characters")
    private String phone;

    /**
     * User's password (BCrypt hashed)
     * NEVER return this field in API responses
     * Can be null until user sets it via email verification
     */
    private String password;

    /**
     * User's address (optional)
     * Can be updated later in profile
     */
    private String address;

    /**
     * User's avatar (optional)
     * Emoji or character representing the user's profile picture
     */
    private String avatar;

    /**
     * User's profile image URL (optional)
     * URL of the profile image stored in AWS S3
     */
    private String profileImageUrl;

    /**
     * Email verification token
     * Generated during registration, used to verify email and set password
     */
    private String verificationToken;

    /**
     * Email verification expiry
     * Token expires after 24 hours
     */
    private LocalDateTime verificationTokenExpiry;

    /**
     * Email verified status
     * True when user clicks verification link and sets password
     */
    private boolean emailVerified = false;

    /**
     * Account enabled status
     * Account is enabled only after email verification
     */
    private boolean enabled = false;

    /**
     * Account blocked status
     * Can be blocked by admin
     */
    private boolean blocked = false;

    /**
     * User role - always USER
     */
    private String role = "USER";

    /**
     * Admin approval status
     * User must be approved by admin before verification email is sent
     */
    private boolean approvedByAdmin = false;

    /**
     * Timestamp - when user was created
     * Automatically managed by Spring Data MongoDB
     */
    @CreatedDate
    private LocalDateTime createdAt;

    /**
     * Timestamp - when user was last updated
     * Automatically updated by Spring Data MongoDB
     */
    @LastModifiedDate
    private LocalDateTime updatedAt;

    /**
     * Constructor without ID (for creating new users)
     * ID will be auto-generated by MongoDB
     */
    public User(String name, String email, String phone, String password, String address) {
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.password = password;
        this.address = address;
    }
}
